function data() {
	return {
			"children": [{
				"name": "Promotions",
				"children": [{
						"name": "axis",
						"children": [{
								"name": "Axes",
								"size": 13
						}, {
								"name": "Axis",
								"size": 24
						}, {
								"name": "AxisGridLine",
								"size": 65
						}, {
								"name": "AxisLabel",
								"size": 63
						}, {
								"name": "CartesianAxes",
								"size": 67
						}]
				}, {
						"name": "controls",
						"children": [{
								"name": "AnchorControl",
								"size": 21
						}, {
								"name": "ClickControl",
								"size": 38
						}, {
								"name": "Control",
								"size": 13
						}, {
								"name": "ControlList",
								"size": 46
						}, {
								"name": "DragControl",
								"size": 26
						}, {
								"name": "ExpandControl",
								"size": 28
						}, {
								"name": "HoverControl",
								"size": 48
						}, {
								"name": "IControl",
								"size": 76
						}, {
								"name": "PanZoomControl",
								"size": 52
						}, {
								"name": "SelectionControl",
								"size": 78
						}, {
								"name": "TooltipControl",
								"size": 84
						}]
				}, {
						"name": "data",
						"children": [{
								"name": "Data",
								"size": 20
						}, {
								"name": "DataList",
								"size": 19
						}, {
								"name": "DataSprite",
								"size": 10
						}, {
								"name": "EdgeSprite",
								"size": 33
						}, {
								"name": "NodeSprite",
								"size": 19
						},{
								"name": "ScaleBinding",
								"size": 11
						}, {
								"name": "Tree",
								"size": 71
						}, {
								"name": "TreeBuilder",
								"size": 99
						}]
				}, {
						"name": "events",
						"children": [{
								"name": "DataEvent",
								"size": 23
						}, {
								"name": "SelectionEvent",
								"size": 18
						}, {
								"name": "TooltipEvent",
								"size": 17
						}, {
								"name": "VisualizationEvent",
								"size": 11
						}]
				}, {
						"name": "legend",
						"children": [{
								"name": "Legend",
								"size": 20
						}, {
								"name": "LegendItem",
								"size": 46
						}, {
								"name": "LegendRange",
								"size": 10
						}]
				}, {
						"name": "operator",
						"children": [{
								"name": "Operator",
								"size": 24
						}, {
								"name": "OperatorList",
								"size": 52
						}, {
								"name": "OperatorSequence",
								"size": 41
						}, {
								"name": "OperatorSwitch",
								"size": 25
						}, {
								"name": "SortOperator",
								"size": 20
						}]
				}, {
						"name": "Visualization",
						"size": 16
				}]
		},{
					"name": "Draft",
					"children": [{
							"name": "interpolate",
							"children": [{
									"name": "ArrayInterpolator",
									"size": 19
							}, {
									"name": "ColorInterpolator",
									"size": 20
							}, {
									"name": "DateInterpolator",
									"size": 13
							}, {
									"name": "Interpolator",
									"size": 87
							}, {
									"name": "MatrixInterpolator",
									"size": 22
							}, {
									"name": "NumberInterpolator",
									"size": 13
							}, {
									"name": "ObjectInterpolator",
									"size": 16
							}, {
									"name": "PointInterpolator",
									"size": 16
							}, {
									"name": "RectangleInterpolator",
									"size": 20
							}]
					},{
						"name": "interpolate",
						"children": [{
								"name": "ArrayInterpolator",
								"size": 19
						}, {
								"name": "ColorInterpolator",
								"size": 20
						}, {
								"name": "DateInterpolator",
								"size": 13
						}, {
								"name": "Interpolator",
								"size": 87
						}, {
								"name": "MatrixInterpolator",
								"size": 22
						}, {
								"name": "NumberInterpolator",
								"size": 13
						}, {
								"name": "ObjectInterpolator",
								"size": 16
						}, {
								"name": "PointInterpolator",
								"size": 16
						}, {
								"name": "RectangleInterpolator",
								"size": 20
						}]
				}]
			}, {
					"name": "Starred",
					"children": [{
							"name": "converters",
							"children": [{
									"name": "Converters",
									"size": 72
							}, {
									"name": "DelimitedTextConverter",
									"size": 42
							}, {
									"name": "GraphMLConverter",
									"size": 98
							}, {
									"name": "IDataConverter",
									"size": 13
							}, {
									"name": "JSONConverter",
									"size": 22
							}]
					},{
						"name": "converters",
						"children": [{
								"name": "Converters",
								"size": 72
						}, {
								"name": "DelimitedTextConverter",
								"size": 42
						}, {
								"name": "GraphMLConverter",
								"size": 98
						}, {
								"name": "IDataConverter",
								"size": 13
						}, {
								"name": "JSONConverter",
								"size": 22
						}]
				}]
			}, {
					"name": "Sent",
					"children": [{
						"name": "converters",
						"children": [{
								"name": "Converters",
								"size": 72
						}, {
								"name": "DelimitedTextConverter",
								"size": 42
						}, {
								"name": "GraphMLConverter",
								"size": 98
						}, {
								"name": "IDataConverter",
								"size": 13
						}, {
								"name": "JSONConverter",
								"size": 22
						}]
				},{
					"name": "converters",
					"children": [{
							"name": "Converters",
							"size": 72
					}, {
							"name": "DelimitedTextConverter",
							"size": 42
					}, {
							"name": "GraphMLConverter",
							"size": 98
					}, {
							"name": "IDataConverter",
							"size": 13
					}, {
							"name": "JSONConverter",
							"size": 22
					}]
			}]
			},{
					"name": "Spam",
					"children": [{
							"name": "methods",
							"children": [{
									"name": "add",
									"size": 59
							}, {
									"name": "and",
									"size": 33
							}, {
									"name": "average",
									"size": 28
							}, {
									"name": "count",
									"size": 27
							}, {
									"name": "distinct",
									"size": 29
							}, {
									"name": "div",
									"size": 59
							}, {
									"name": "eq",
									"size": 59
							}, {
									"name": "fn",
									"size": 46
							}, {
									"name": "gt",
									"size": 60
							}, {
									"name": "gte",
									"size": 62
							}, {
									"name": "iff",
									"size": 74
							}, {
									"name": "isa",
									"size": 46
							}, {
									"name": "lt",
									"size": 59
							}, {
									"name": "lte",
									"size": 61
							}, {
									"name": "max",
									"size": 28
							}, {
									"name": "min",
									"size": 28
							}, {
									"name": "mod",
									"size": 59
							}, {
									"name": "mul",
									"size": 60
							}, {
									"name": "neq",
									"size": 59
							}, {
									"name": "not",
									"size": 38
							}, {
									"name": "or",
									"size": 32
							}, {
									"name": "orderby",
									"size": 30
							}, {
									"name": "range",
									"size": 77
							}, {
									"name": "select",
									"size": 29
							}, {
									"name": "stddev",
									"size": 36
							}, {
									"name": "sub",
									"size": 60
							}, {
									"name": "sum",
									"size": 28
							}, {
									"name": "update",
									"size": 30
							}, {
									"name": "variance",
									"size": 33
							}, {
									"name": "where",
									"size": 29
							}, {
									"name": "xor",
									"size": 35
							}, {
									"name": "_",
									"size": 264
							}]
					},{
						"name": "methods",
						"children": [{
								"name": "add",
								"size": 59
						}, {
								"name": "and",
								"size": 33
						}, {
								"name": "average",
								"size": 28
						}, {
								"name": "count",
								"size": 27
						}, {
								"name": "distinct",
								"size": 29
						}, {
								"name": "div",
								"size": 59
						}, {
								"name": "eq",
								"size": 59
						}, {
								"name": "fn",
								"size": 46
						}, {
								"name": "gt",
								"size": 60
						}, {
								"name": "gte",
								"size": 62
						}, {
								"name": "iff",
								"size": 74
						}, {
								"name": "isa",
								"size": 46
						}, {
								"name": "lt",
								"size": 59
						}, {
								"name": "lte",
								"size": 61
						}, {
								"name": "max",
								"size": 28
						}, {
								"name": "min",
								"size": 28
						}, {
								"name": "mod",
								"size": 59
						}, {
								"name": "mul",
								"size": 60
						}, {
								"name": "neq",
								"size": 59
						}, {
								"name": "not",
								"size": 38
						}, {
								"name": "or",
								"size": 32
						}, {
								"name": "orderby",
								"size": 30
						}, {
								"name": "range",
								"size": 77
						}, {
								"name": "select",
								"size": 29
						}, {
								"name": "stddev",
								"size": 36
						}, {
								"name": "sub",
								"size": 60
						}, {
								"name": "sum",
								"size": 28
						}, {
								"name": "update",
								"size": 30
						}, {
								"name": "variance",
								"size": 33
						}, {
								"name": "where",
								"size": 29
						}, {
								"name": "xor",
								"size": 35
						}, {
								"name": "_",
								"size": 264
						}]
				}]
			}, {
					"name": "Updates",
					"children": [{
						"name": "interpolate",
						"children": [{
								"name": "ArrayInterpolator",
								"size": 19
						}, {
								"name": "ColorInterpolator",
								"size": 20
						}, {
								"name": "DateInterpolator",
								"size": 13
						}, {
								"name": "Interpolator",
								"size": 87
						}, {
								"name": "MatrixInterpolator",
								"size": 22
						}, {
								"name": "NumberInterpolator",
								"size": 13
						}, {
								"name": "ObjectInterpolator",
								"size": 16
						}, {
								"name": "PointInterpolator",
								"size": 16
						}, {
								"name": "RectangleInterpolator",
								"size": 20
						}]
				},{
					"name": "interpolate",
					"children": [{
							"name": "ArrayInterpolator",
							"size": 19
					}, {
							"name": "ColorInterpolator",
							"size": 20
					}, {
							"name": "DateInterpolator",
							"size": 13
					}, {
							"name": "Interpolator",
							"size": 87
					}, {
							"name": "MatrixInterpolator",
							"size": 22
					}, {
							"name": "NumberInterpolator",
							"size": 13
					}, {
							"name": "ObjectInterpolator",
							"size": 16
					}, {
							"name": "PointInterpolator",
							"size": 16
					}, {
							"name": "RectangleInterpolator",
							"size": 20
					}]
			}]
			}, {
					"name": "Social",
					"children": [{
							"name": "Instagram",
							"children": [{
									"name": "FibonacciHeap",
									"size": 93
									
							}, {
									"name": "HeapNode",
									"size": 12
							}]
					}, {
							"name": "Youtube",
							"children": [{
									"name": "DenseMatrix",
									"size": 31
							}, {
									"name": "IMatrix",
									"size": 28
							}, {
									"name": "SparseMatrix",
									"size": 33
							}]
					},{
							"name": "Facebook",
							"children": [{
									"name": "ColorPalette",
									"size": 63
							}, {
									"name": "Palette",
									"size": 12
							}, {
									"name": "ShapePalette",
									"size": 20
							}, {
									"name": "SizePalette",
									"size": 22
							}]
					},{
						"name": "Google+",
						"children": [{
								"name": "ColorPalette",
								"size": 63
						}, {
								"name": "Palette",
								"size": 12
						}, {
								"name": "ShapePalette",
								"size": 20
						}, {
								"name": "SizePalette",
								"size": 22
						}]
				},{
					"name": "Twitter",
					"children": [{
							"name": "ColorPalette",
							"size": 63
					}, {
							"name": "Palette",
							"size": 12
					}, {
							"name": "ShapePalette",
							"size": 20
					}, {
							"name": "SizePalette",
							"size": 22
					}]
			},{
				"name": "Good Reads",
				"children": [{
						"name": "ColorPalette",
						"size": 63
				}, {
						"name": "Palette",
						"size": 12
				}, {
						"name": "ShapePalette",
						"size": 20
				}, {
						"name": "SizePalette",
						"size": 22
				}]
		}]
			}]
	}
}


export default data;
